// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/company/About.vue')['default']
    Banner: typeof import('./components/Banner.vue')['default']
    copy: typeof import('./components/home/VideoBanner copy.vue')['default']
    Hero: typeof import('./components/home/Hero.vue')['default']
    PreferredVendors: typeof import('./components/company/PreferredVendors.vue')['default']
    README: typeof import('./components/README.md')['default']
    Reviews: typeof import('./components/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Team: typeof import('./components/company/Team.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    VideoBanner: typeof import('./components/home/VideoBanner.vue')['default']
    Welcome: typeof import('./components/home/Welcome.vue')['default']
  }
}
